FROM node:24-alpine AS build
WORKDIR /app
COPY Jarash.Web/package*.json ./
RUN npm ci
COPY Jarash.Web/ .
RUN npm run build

FROM nginx:1.30-alpine AS final
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
